name: Sample Workflow

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Run the reusable workflow
              uses: AnsgarH1/github-actions-versioning-test@main