name: Sample Workflow

on:
    push:


jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            message: ${{ steps.run-action.outputs.message }}
            version: ${{ steps.run-action.outputs.version }}
        steps:

            - name: Run the reusable workflow
              uses: AnsgarH1/github-actions-versioning-test@v1
    